In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('Energy_Indicators.xlsx')
data.shape

(282, 6)

In [3]:
data.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,Environmental Indicators: Energy,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Energy Supply and Renewable Electricity Produc...,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Last update: December 2015
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Choose a country from the following drop-down ...,NaN,NaN,Andorra
7,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,Country,Energy Supply,Energy Supply per capita,Renewable Electricity Production
9,NaN,NaN,NaN,Petajoules,Gigajoules,%
10,NaN,NaN,Andorra,9,121,88.69565
11,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,website: http://unstats.un.org/unsd/ENVIRONMEN...
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,Energy Supply,Energy Supply per capita,Renewable Electricity Production
16,NaN,NaN,NaN,Petajoules,Gigajoules,%
17,NaN,Afghanistan,Afghanistan,321,10,78.66928
18,NaN,Albania,Albania,102,35,100
19,NaN,Algeria,Algeria,1959,51,0.55101

In [4]:
data.drop(data.loc[0:16].index,inplace=True)

In [5]:
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
17,NaN,Afghanistan,Afghanistan,321,10,78.66928
18,NaN,Albania,Albania,102,35,100
19,NaN,Algeria,Algeria,1959,51,0.55101
20,NaN,American Samoa,American Samoa,...,...,0.641026
21,NaN,Andorra,Andorra,9,121,88.69565
...,...,...,...,...,...,...
277,NaN,… denotes no data available.,NaN,NaN,NaN,NaN
278,NaN,NaN,NaN,NaN,NaN,NaN
279,NaN,Data Quality:,NaN,NaN,NaN,NaN
280,NaN,The data are compiled primarily from the annua...,NaN,NaN,NaN,NaN
281,NaN,"For more information, visit http://unstats.un....",NaN,NaN,NaN,NaN

In [6]:
data.drop(data.loc[244:282].index,inplace=True)

In [7]:
data.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
239,NaN,Viet Nam,Viet Nam,2554,28,45.32152
240,NaN,Wallis and Futuna Islands,Wallis and Futuna Islands,0,26,0
241,NaN,Yemen,Yemen,344,13,0
242,NaN,Zambia,Zambia,400,26,99.71467
243,NaN,Zimbabwe,Zimbabwe,480,32,52.53612

In [8]:
data.drop('Unnamed: 0',axis =1)
data.drop(['Unnamed: 0','Unnamed: 1'],axis = 1,inplace=True)

In [9]:
data

                    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
17                 Afghanistan        321         10   78.66928
18                     Albania        102         35        100
19                     Algeria       1959         51    0.55101
20              American Samoa        ...        ...   0.641026
21                     Andorra          9        121   88.69565
..                         ...        ...        ...        ...
239                   Viet Nam       2554         28   45.32152
240  Wallis and Futuna Islands          0         26          0
241                      Yemen        344         13          0
242                     Zambia        400         26   99.71467
243                   Zimbabwe        480         32   52.53612

[227 rows x 4 columns]

In [10]:
data.rename(columns={'Unnamed: 2':'Country',
                   'Unnamed: 3':'Energy Supply in Gigajoules',
                   'Unnamed: 4':'Energy Supply per Capita',
                   'Unnamed: 5':'% Renewable'},inplace=True)

In [11]:
data

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
17,Afghanistan,321,10,78.66928
18,Albania,102,35,100
19,Algeria,1959,51,0.55101
20,American Samoa,...,...,0.641026
21,Andorra,9,121,88.69565
...,...,...,...,...
239,Viet Nam,2554,28,45.32152
240,Wallis and Futuna Islands,0,26,0
241,Yemen,344,13,0
242,Zambia,400,26,99.71467
243,Zimbabwe,480,32,52.53612

In [12]:
Energy=pd.DataFrame(data)
Energy.reset_index(drop=True,inplace=True)

In [13]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,321,10,78.66928
1,Albania,102,35,100
2,Algeria,1959,51,0.55101
3,American Samoa,...,...,0.641026
4,Andorra,9,121,88.69565
...,...,...,...,...
222,Viet Nam,2554,28,45.32152
223,Wallis and Futuna Islands,0,26,0
224,Yemen,344,13,0
225,Zambia,400,26,99.71467
226,Zimbabwe,480,32,52.53612

In [14]:
Energy.isna().sum()

Country                        0
Energy Supply in Gigajoules    0
Energy Supply per Capita       0
% Renewable                    0
dtype: int64

In [16]:
Energy['Energy Supply in Gigajoules']= pd.to_numeric(Energy['Energy Supply in Gigajoules'],errors = 'coerce')
Energy['Energy Supply per Capita']= pd.to_numeric(Energy['Energy Supply per Capita'],errors = 'coerce')
Energy['% Renewable']= pd.to_numeric(Energy['% Renewable'],errors = 'coerce')

In [17]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
...,...,...,...,...
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [18]:
pd.set_option('display.max_rows',None)

In [19]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
5,Angola,642.0,27.0,70.909090
6,Anguilla,2.0,136.0,0.000000
7,Antigua and Barbuda,8.0,84.0,0.000000
8,Argentina,3378.0,79.0,24.064520
9,Armenia,143.0,48.0,28.236060
10,Aruba,12.0,120.0,14.870690
11,Australia1,5386.0,231.0,11.810810
12,Austria,1391.0,164.0,72.452820
13,Azerbaijan,567.0,60.0,6.384345
14,Bahamas,45.0,118.0,0.000000
15,Bahrain,574.0,425.0,0.000000
16,Bangladesh,1625.0,10.0,1.966329
17,Barbados,19.0,69.0,0.000000
18,Belarus,1142.0,120.0,0.463389
19,Belgium,2338.0,210.0,9.959739
20,Belize,13.0,39.0,64.690030
21,Benin,170.0,16.0,0.000000
22,Bermuda,6.0,88.0,0.000000
23,Bhutan,63.0,83.0,100.000000
24,Bolivia (Plurinational State of),336.0,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.0,213.0,0.000000
26,Bosnia and Herzegovina,266.0,70.0,41.464670
27,Botswana,86.0,39.0,0.131406
28,Brazil,12149.0,59.0,69.648030
29,British Virgin Islands,2.0,85.0,0.000000
30,Brunei Darussalam,127.0,310.0,0.045434
31,Bulgaria,703.0,97.0,17.234610
32,Burkina Faso,164.0,10.0,14.500680
33,Burundi,58.0,6.0,86.792450
34,Cabo Verde,7.0,15.0,21.227620
35,Cambodia,250.0,17.0,57.311590
36,Cameroon,307.0,14.0,70.886260
37,Canada,10431.0,296.0,61.945430
38,Cayman Islands,8.0,131.0,0.000000
39,Central African Republic,23.0,5.0,85.635360
40,Chad,77.0,6.0,0.000000
41,Chile,1613.0,92.0,28.006570
42,China2,127191.0,93.0,19.754910
43,"China, Hong Kong Special Administrative Region3",585.0,82.0,0.000000
44,"China, Macao Special Administrative Region4",47.0,83.0,0.000000
45,Colombia,1513.0,32.0,63.002840
46,Comoros,5.0,7.0,11.627910
47,Congo,102.0,23.0,57.748870
48,Cook Islands,1.0,48.0,0.000000
49,Costa Rica,222.0,47.0,88.736420
50,Côte d'Ivoire,547.0,25.0,22.822780
51,Croatia,321.0,75.0,64.284120
52,Cuba,585.0,51.0,0.663532
53,Curaçao,78.0,502.0,0.000000
54,Cyprus,82.0,71.0,6.480186
55,Czech Republic,1751.0,166.0,7.067134
56,Democratic People's Republic of Korea,612.0,25.0,70.180290
57,Democratic Republic of the Congo,888.0,12.0,99.594300
58,Denmark5,725.0,129.0,33.537660
59,Djibouti,11.0,13.0,0.000000
60,Dominica,2.0,28.0,36.633660
61,Dominican Republic,339.0,33.0,11.250600
62,Ecuador,680.0,43.0,47.714860
63,Egypt,3422.0,39.0,8.805713
64,El Salvador,176.0,29.0,56.445050
65,Equatorial Guinea,73.0,91.0,6.363636
66,Eritrea,34.0,7.0,0.550964
67,Estonia,258.0,195.0,4.180791
68,Ethiopia,1394.0,15.0,99.908250
69,Faeroe Islands,9.0,179.0,38.566550
70,Falkland Islands (Malvinas),1.0,258.0,33.333330
71,Fiji,31.0,36.0,62.004660
72,Finland,1374.0,252.0,19.536570
73,France6,10597.0,166.0,17.020280
74,French Guiana,13.0,52.0,62.004660
75,French Polynesia,12.0,44.0,26.855600
76,Gabon,99.0,60.0,37.500000
77,Gambia,14.0,7.0,0.000000
78,Georgia,163.0,40.0,82.224870
79,Germany,13261.0,165.0,17.901530
80,Ghana,316.0,12.0,63.102630
81,Gibraltar,8.0,245.0,0.000000
82,Greece,993.0,90.0,24.795280
83,Greenland7,9.0,166.0,78.125000
84,Grenada,5.0,43.0,0.000000
85,Guadeloupe,33.0,70.0,14.814810
86,Guam,NaN,NaN,0.000000
87,Guatemala,452.0,29.0,49.521680
88,Guernsey,0.0,6.0,0.000000
89,Guinea,145.0,12.0,48.442210
90,Guinea-Bissau,29.0,17.0,0.000000
91,Guyana,34.0,45.0,0.000000
92,Haiti,172.0,16.0,12.760180
93,Honduras,217.0,28.0,37.763190
94,Hungary,947.0,95.0,3.263634
95,Iceland,312.0,957.0,99.972400
96,India,33195.0,26.0,14.969080
97,Indonesia8,8754.0,35.0,12.189040
98,Iran (Islamic Republic of),9172.0,119.0,5.707721
99,Iraq,2077.0,61.0,7.871554
100,Ireland,548.0,117.0,20.921060
101,Isle of Man,0.0,4.0,0.793651
102,Israel,997.0,128.0,0.872525
103,Italy9,6530.0,109.0,33.667230
104,Jamaica,108.0,39.0,5.615602
105,Japan10,18984.0,149.0,10.232820
106,Jersey,3.0,34.0,0.000000
107,Jordan,325.0,45.0,0.335979
108,Kazakhstan,3548.0,208.0,8.112784
109,Kenya,873.0,20.0,73.757100
110,Kiribati,1.0,8.0,0.000000
111,Kuwait11,1475.0,410.0,0.000000
112,Kyrgyzstan,167.0,29.0,93.476550
113,Lao People's Democratic Republic,85.0,13.0,93.290090
114,Latvia,183.0,91.0,48.832340
115,Lebanon,289.0,55.0,6.610478
116,Lesotho,48.0,23.0,100.000000
117,Liberia,83.0,19.0,0.000000
118,Libya,707.0,113.0,0.000000
119,Liechtenstein,3.0,79.0,96.470590
120,Lithuania,282.0,95.0,41.033180
121,Luxembourg,168.0,307.0,45.533240
122,Madagascar,166.0,7.0,50.815560
123,Malawi,101.0,6.0,89.135650
124,Malaysia,3417.0,116.0,7.754589
125,Maldives,15.0,43.0,0.000000
126,Mali,66.0,4.0,64.768210
127,Malta,31.0,75.0,1.419698
128,Marshall Islands,1.0,28.0,0.000000
129,Martinique,33.0,84.0,2.607710
130,Mauritania,51.0,13.0,0.000000
131,Mauritius,58.0,46.0,3.531856
132,Mexico,7944.0,64.0,12.913400
133,Micronesia (Federated States of),2.0,21.0,2.941176
134,Mongolia,475.0,166.0,0.000000
135,Montenegro,42.0,67.0,65.581520
136,Montserrat,1.0,153.0,0.000000
137,Morocco,796.0,23.0,15.891800
138,Mozambique,469.0,18.0,94.630870
139,Myanmar,682.0,13.0,72.042130
140,Namibia,63.0,27.0,95.794390
141,Nauru,1.0,60.0,0.000000
142,Nepal,458.0,16.0,99.680510
143,Netherlands12,3199.0,190.0,6.324659
144,New Caledonia,51.0,200.0,20.430970
145,New Zealand,876.0,196.0,72.873130
146,Nicaragua,149.0,25.0,40.763870
147,Niger,87.0,5.0,0.000000
148,Nigeria,5589.0,32.0,18.390250
149,Niue,0.0,65.0,0.000000
150,Northern Mariana Islands,NaN,NaN,0.000000
151,Norway,1388.0,273.0,97.635580
152,Oman,1015.0,260.0,0.000000
153,Pakistan,2868.0,16.0,31.876840
154,Palau,3.0,152.0,18.750000
155,Panama,158.0,42.0,57.509480
156,Papua New Guinea,144.0,20.0,23.946360
157,Paraguay,228.0,35.0,99.995030
158,Peru,858.0,28.0,51.968610
159,Philippines,1781.0,18.0,26.172640
160,Poland,4121.0,107.0,5.537899
161,Portugal13,899.0,86.0,53.340300
162,Puerto Rico,56.0,15.0,1.080808
163,Qatar,1396.0,664.0,0.000000
164,Republic of Korea,11007.0,221.0,2.279353
165,Republic of Moldova,93.0,23.0,5.082873
166,Réunion,59.0,70.0,28.297190
167,Romania,1339.0,68.0,34.384500
168,Russian Federation,30709.0,214.0,17.288680
169,Rwanda,95.0,9.0,35.835350
170,Saint Helena,0.0,40.0,9.090909
171,Saint Kitts and Nevis,4.0,73.0,0.000000
172,Saint Lucia,6.0,33.0,0.000000
173,Saint Pierre and Miquelon,1.0,162.0,2.127660
174,Saint Vincent and the Grenadines,3.0,28.0,16.666670
175,Samoa,4.0,22.0,31.355930
176,Sao Tome and Principe,3.0,14.0,10.447760
177,Saudi Arabia14,7985.0,264.0,0.000352
178,Senegal,154.0,11.0,1.998237
179,Serbia15,618.0,69.0,27.216190
180,Seychelles,9.0,94.0,1.977401
181,Sierra Leone,67.0,11.0,64.024390
182,Singapore,1120.0,207.0,0.000000
183,Sint Maarten (Dutch part),12.0,327.0,0.000000
184,Slovakia,711.0,131.0,20.217120
185,Slovenia,287.0,139.0,31.864240
186,Solomon Islands,6.0,11.0,0.000000
187,Somalia,126.0,12.0,0.000000
188,South Africa,6341.0,119.0,1.687019
189,South Sudan,28.0,2.0,0.423729
190,Spain16,4923.0,106.0,37.968590
191,Sri Lanka,388.0,19.0,59.573230
192,State of Palestine,61.0,14.0,0.000000
193,Sudan,608.0,16.0,78.410480
194,Suriname,34.0,65.0,22.023810
195,Swaziland,49.0,39.0,40.677970
196,Sweden,2044.0,212.0,46.598460
197,Switzerland17,1113.0,136.0,57.745480
198,Syrian Arab Republic,542.0,28.0,11.568270
199,Tajikistan,106.0,13.0,99.742920
200,Thailand,5336.0,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,117.0,56.0,26.140470
202,Timor-Leste,7.0,6.0,0.000000
203,Togo,134.0,19.0,80.180180
204,Tonga,3.0,28.0,0.000000
205,Trinidad and Tobago,824.0,611.0,0.000000
206,Tunisia,430.0,39.0,3.492547
207,Turkey,4897.0,64.0,28.536690
208,Turkmenistan,1102.0,210.0,0.000000
209,Turks and Caicos Islands,3.0,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,452.0,12.0,68.018180
212,Ukraine18,4844.0,107.0,8.067312
213,United Arab Emirates,2710.0,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7920.0,124.0,10.600470
215,United Republic of Tanzania,994.0,20.0,31.072840
216,United States of America20,90838.0,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,196.0,58.0,71.605040
219,Uzbekistan,1798.0,62.0,21.328410
220,Vanuatu,3.0,10.0,14.705880
221,Venezuela (Bolivarian Republic of),2871.0,95.0,67.834520
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [20]:
# Energy.loc[221]={'Country':'Venezuela'}
# Energy.loc[216]={'Country':'United States'}
# Energy.loc[214]={'Country':'United Kingdom'}
# Energy.loc[212]={'Country':'Ukraine'}
# Energy.loc[197]={'Country':'Switzerland'}
# Energy.loc[190]={'Country':'Spain'}
# Energy.loc[183]={'Country':'Sint Maarten '}
# Energy.loc[179]={'Country':'Serbia'}
# Energy.loc[177]={'Country':'Saudi Arabia'}
# Energy.loc[161]={'Country':'Portugal'}
# Energy.loc[133]={'Country':'Micronesia '}
# Energy.loc[111]={'Country':'Kuwait'}
# Energy.loc[105]={'Country':'Japan'}
# Energy.loc[103]={'Country':'Italy'}
# Energy.loc[98]={'Country':'Iran'}
# Energy.loc[97]={'Country':'Indonesia'}
# Energy.loc[83]={'Country':'Greenland'}
# Energy.loc[73]={'Country':'France'}
# Energy.loc[70]={'Country':'Falkland Islands'}
# Energy.loc[58]={'Country':'Denmark'}
# Energy.loc[44]={'Country':'China, Macao '}
# Energy.loc[43]={'Country':'Hong Kong '}
# Energy.loc[42]={'Country':'China'}
# Energy.loc[24]={'Country':'Bolivia '}
# Energy.loc[11]={'Country':'Australia'}

In [21]:
Energy['Country'].replace(['Australia1'],['Australia'],inplace=True)
Energy['Country'].replace(['Venezuela (Bolivarian Republic of)'],['Venezuela'],inplace=True)
Energy['Country'].replace(['United States of America20'],['United States'],inplace=True)
Energy['Country'].replace(['United Kingdom of Great Britain and Northern I...'],['United Kingdom'],inplace=True)
Energy['Country'].replace(['Ukraine1'],['Ukraine'],inplace=True)
Energy['Country'].replace(['Switzerland17'],['Switzerland'],inplace=True)
Energy['Country'].replace(['Spain16'],['Spain'],inplace=True)
Energy['Country'].replace(['Sint Maarten (Dutch part)'],['Sint Maarten'],inplace=True)
Energy['Country'].replace(['Serbia15'],['Serbia'],inplace=True)
Energy['Country'].replace(['Saudi Arabia14'],['Saudi Arabia'],inplace=True)
Energy['Country'].replace(['Portugal13'],['Portugal'],inplace=True)
Energy['Country'].replace(['Netherlands12'],['Netherlands'],inplace=True)
Energy['Country'].replace(['Micronesia (Federated States of)'],['Micronesia '],inplace=True)
Energy['Country'].replace(['Kuwait11'],['Kuwait'],inplace=True)
Energy['Country'].replace(['Japan10'],['Japan'],inplace=True)
Energy['Country'].replace(['Italy9'],['Italy'],inplace=True)
Energy['Country'].replace(['Iran (Islamic Republic of)'],['Iran '],inplace=True)
Energy['Country'].replace(['Indonesia8'],['Indonesia'],inplace=True)
Energy['Country'].replace(['Greenland7'],['Greenland'],inplace=True)
Energy['Country'].replace(['France6'],['France'],inplace=True)
Energy['Country'].replace(['Falkland Islands (Malvinas)'],['Falkland Islands'],inplace=True)
Energy['Country'].replace(['Denmark5'],['Denmark'],inplace=True)
Energy['Country'].replace(['China, Macao Special Administrative Region4'],['China,Macao'],inplace=True)
Energy['Country'].replace(['China, Hong Kong Special Administrative Region3'],[' Hong Kong'],inplace=True)
Energy['Country'].replace(['China2'],['China'],inplace=True)
Energy['Country'].replace(['Bolivia (Plurinational State of)'],['Bolivia'],inplace=True)
Energy['Country'].replace(['China2'],['China'],inplace=True)

In [22]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
5,Angola,642.0,27.0,70.909090
6,Anguilla,2.0,136.0,0.000000
7,Antigua and Barbuda,8.0,84.0,0.000000
8,Argentina,3378.0,79.0,24.064520
9,Armenia,143.0,48.0,28.236060
10,Aruba,12.0,120.0,14.870690
11,Australia,5386.0,231.0,11.810810
12,Austria,1391.0,164.0,72.452820
13,Azerbaijan,567.0,60.0,6.384345
14,Bahamas,45.0,118.0,0.000000
15,Bahrain,574.0,425.0,0.000000
16,Bangladesh,1625.0,10.0,1.966329
17,Barbados,19.0,69.0,0.000000
18,Belarus,1142.0,120.0,0.463389
19,Belgium,2338.0,210.0,9.959739
20,Belize,13.0,39.0,64.690030
21,Benin,170.0,16.0,0.000000
22,Bermuda,6.0,88.0,0.000000
23,Bhutan,63.0,83.0,100.000000
24,Bolivia,336.0,32.0,31.477120
25,"Bonaire, Sint Eustatius and Saba",5.0,213.0,0.000000
26,Bosnia and Herzegovina,266.0,70.0,41.464670
27,Botswana,86.0,39.0,0.131406
28,Brazil,12149.0,59.0,69.648030
29,British Virgin Islands,2.0,85.0,0.000000
30,Brunei Darussalam,127.0,310.0,0.045434
31,Bulgaria,703.0,97.0,17.234610
32,Burkina Faso,164.0,10.0,14.500680
33,Burundi,58.0,6.0,86.792450
34,Cabo Verde,7.0,15.0,21.227620
35,Cambodia,250.0,17.0,57.311590
36,Cameroon,307.0,14.0,70.886260
37,Canada,10431.0,296.0,61.945430
38,Cayman Islands,8.0,131.0,0.000000
39,Central African Republic,23.0,5.0,85.635360
40,Chad,77.0,6.0,0.000000
41,Chile,1613.0,92.0,28.006570
42,China,127191.0,93.0,19.754910
43,Hong Kong,585.0,82.0,0.000000
44,"China,Macao",47.0,83.0,0.000000
45,Colombia,1513.0,32.0,63.002840
46,Comoros,5.0,7.0,11.627910
47,Congo,102.0,23.0,57.748870
48,Cook Islands,1.0,48.0,0.000000
49,Costa Rica,222.0,47.0,88.736420
50,Côte d'Ivoire,547.0,25.0,22.822780
51,Croatia,321.0,75.0,64.284120
52,Cuba,585.0,51.0,0.663532
53,Curaçao,78.0,502.0,0.000000
54,Cyprus,82.0,71.0,6.480186
55,Czech Republic,1751.0,166.0,7.067134
56,Democratic People's Republic of Korea,612.0,25.0,70.180290
57,Democratic Republic of the Congo,888.0,12.0,99.594300
58,Denmark,725.0,129.0,33.537660
59,Djibouti,11.0,13.0,0.000000
60,Dominica,2.0,28.0,36.633660
61,Dominican Republic,339.0,33.0,11.250600
62,Ecuador,680.0,43.0,47.714860
63,Egypt,3422.0,39.0,8.805713
64,El Salvador,176.0,29.0,56.445050
65,Equatorial Guinea,73.0,91.0,6.363636
66,Eritrea,34.0,7.0,0.550964
67,Estonia,258.0,195.0,4.180791
68,Ethiopia,1394.0,15.0,99.908250
69,Faeroe Islands,9.0,179.0,38.566550
70,Falkland Islands,1.0,258.0,33.333330
71,Fiji,31.0,36.0,62.004660
72,Finland,1374.0,252.0,19.536570
73,France,10597.0,166.0,17.020280
74,French Guiana,13.0,52.0,62.004660
75,French Polynesia,12.0,44.0,26.855600
76,Gabon,99.0,60.0,37.500000
77,Gambia,14.0,7.0,0.000000
78,Georgia,163.0,40.0,82.224870
79,Germany,13261.0,165.0,17.901530
80,Ghana,316.0,12.0,63.102630
81,Gibraltar,8.0,245.0,0.000000
82,Greece,993.0,90.0,24.795280
83,Greenland,9.0,166.0,78.125000
84,Grenada,5.0,43.0,0.000000
85,Guadeloupe,33.0,70.0,14.814810
86,Guam,NaN,NaN,0.000000
87,Guatemala,452.0,29.0,49.521680
88,Guernsey,0.0,6.0,0.000000
89,Guinea,145.0,12.0,48.442210
90,Guinea-Bissau,29.0,17.0,0.000000
91,Guyana,34.0,45.0,0.000000
92,Haiti,172.0,16.0,12.760180
93,Honduras,217.0,28.0,37.763190
94,Hungary,947.0,95.0,3.263634
95,Iceland,312.0,957.0,99.972400
96,India,33195.0,26.0,14.969080
97,Indonesia,8754.0,35.0,12.189040
98,Iran,9172.0,119.0,5.707721
99,Iraq,2077.0,61.0,7.871554
100,Ireland,548.0,117.0,20.921060
101,Isle of Man,0.0,4.0,0.793651
102,Israel,997.0,128.0,0.872525
103,Italy,6530.0,109.0,33.667230
104,Jamaica,108.0,39.0,5.615602
105,Japan,18984.0,149.0,10.232820
106,Jersey,3.0,34.0,0.000000
107,Jordan,325.0,45.0,0.335979
108,Kazakhstan,3548.0,208.0,8.112784
109,Kenya,873.0,20.0,73.757100
110,Kiribati,1.0,8.0,0.000000
111,Kuwait,1475.0,410.0,0.000000
112,Kyrgyzstan,167.0,29.0,93.476550
113,Lao People's Democratic Republic,85.0,13.0,93.290090
114,Latvia,183.0,91.0,48.832340
115,Lebanon,289.0,55.0,6.610478
116,Lesotho,48.0,23.0,100.000000
117,Liberia,83.0,19.0,0.000000
118,Libya,707.0,113.0,0.000000
119,Liechtenstein,3.0,79.0,96.470590
120,Lithuania,282.0,95.0,41.033180
121,Luxembourg,168.0,307.0,45.533240
122,Madagascar,166.0,7.0,50.815560
123,Malawi,101.0,6.0,89.135650
124,Malaysia,3417.0,116.0,7.754589
125,Maldives,15.0,43.0,0.000000
126,Mali,66.0,4.0,64.768210
127,Malta,31.0,75.0,1.419698
128,Marshall Islands,1.0,28.0,0.000000
129,Martinique,33.0,84.0,2.607710
130,Mauritania,51.0,13.0,0.000000
131,Mauritius,58.0,46.0,3.531856
132,Mexico,7944.0,64.0,12.913400
133,Micronesia,2.0,21.0,2.941176
134,Mongolia,475.0,166.0,0.000000
135,Montenegro,42.0,67.0,65.581520
136,Montserrat,1.0,153.0,0.000000
137,Morocco,796.0,23.0,15.891800
138,Mozambique,469.0,18.0,94.630870
139,Myanmar,682.0,13.0,72.042130
140,Namibia,63.0,27.0,95.794390
141,Nauru,1.0,60.0,0.000000
142,Nepal,458.0,16.0,99.680510
143,Netherlands,3199.0,190.0,6.324659
144,New Caledonia,51.0,200.0,20.430970
145,New Zealand,876.0,196.0,72.873130
146,Nicaragua,149.0,25.0,40.763870
147,Niger,87.0,5.0,0.000000
148,Nigeria,5589.0,32.0,18.390250
149,Niue,0.0,65.0,0.000000
150,Northern Mariana Islands,NaN,NaN,0.000000
151,Norway,1388.0,273.0,97.635580
152,Oman,1015.0,260.0,0.000000
153,Pakistan,2868.0,16.0,31.876840
154,Palau,3.0,152.0,18.750000
155,Panama,158.0,42.0,57.509480
156,Papua New Guinea,144.0,20.0,23.946360
157,Paraguay,228.0,35.0,99.995030
158,Peru,858.0,28.0,51.968610
159,Philippines,1781.0,18.0,26.172640
160,Poland,4121.0,107.0,5.537899
161,Portugal,899.0,86.0,53.340300
162,Puerto Rico,56.0,15.0,1.080808
163,Qatar,1396.0,664.0,0.000000
164,Republic of Korea,11007.0,221.0,2.279353
165,Republic of Moldova,93.0,23.0,5.082873
166,Réunion,59.0,70.0,28.297190
167,Romania,1339.0,68.0,34.384500
168,Russian Federation,30709.0,214.0,17.288680
169,Rwanda,95.0,9.0,35.835350
170,Saint Helena,0.0,40.0,9.090909
171,Saint Kitts and Nevis,4.0,73.0,0.000000
172,Saint Lucia,6.0,33.0,0.000000
173,Saint Pierre and Miquelon,1.0,162.0,2.127660
174,Saint Vincent and the Grenadines,3.0,28.0,16.666670
175,Samoa,4.0,22.0,31.355930
176,Sao Tome and Principe,3.0,14.0,10.447760
177,Saudi Arabia,7985.0,264.0,0.000352
178,Senegal,154.0,11.0,1.998237
179,Serbia,618.0,69.0,27.216190
180,Seychelles,9.0,94.0,1.977401
181,Sierra Leone,67.0,11.0,64.024390
182,Singapore,1120.0,207.0,0.000000
183,Sint Maarten,12.0,327.0,0.000000
184,Slovakia,711.0,131.0,20.217120
185,Slovenia,287.0,139.0,31.864240
186,Solomon Islands,6.0,11.0,0.000000
187,Somalia,126.0,12.0,0.000000
188,South Africa,6341.0,119.0,1.687019
189,South Sudan,28.0,2.0,0.423729
190,Spain,4923.0,106.0,37.968590
191,Sri Lanka,388.0,19.0,59.573230
192,State of Palestine,61.0,14.0,0.000000
193,Sudan,608.0,16.0,78.410480
194,Suriname,34.0,65.0,22.023810
195,Swaziland,49.0,39.0,40.677970
196,Sweden,2044.0,212.0,46.598460
197,Switzerland,1113.0,136.0,57.745480
198,Syrian Arab Republic,542.0,28.0,11.568270
199,Tajikistan,106.0,13.0,99.742920
200,Thailand,5336.0,79.0,4.305189
201,The former Yugoslav Republic of Macedonia,117.0,56.0,26.140470
202,Timor-Leste,7.0,6.0,0.000000
203,Togo,134.0,19.0,80.180180
204,Tonga,3.0,28.0,0.000000
205,Trinidad and Tobago,824.0,611.0,0.000000
206,Tunisia,430.0,39.0,3.492547
207,Turkey,4897.0,64.0,28.536690
208,Turkmenistan,1102.0,210.0,0.000000
209,Turks and Caicos Islands,3.0,85.0,0.000000
210,Tuvalu,NaN,NaN,0.000000
211,Uganda,452.0,12.0,68.018180
212,Ukraine18,4844.0,107.0,8.067312
213,United Arab Emirates,2710.0,300.0,0.000000
214,United Kingdom of Great Britain and Northern I...,7920.0,124.0,10.600470
215,United Republic of Tanzania,994.0,20.0,31.072840
216,United States,90838.0,286.0,11.570980
217,United States Virgin Islands,NaN,NaN,0.000000
218,Uruguay,196.0,58.0,71.605040
219,Uzbekistan,1798.0,62.0,21.328410
220,Vanuatu,3.0,10.0,14.705880
221,Venezuela,2871.0,95.0,67.834520
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [23]:
Energy['Country'].replace(['Republic of Korea'],['Korea'],inplace=True)

In [24]:
Energy.iloc[214]

Country                        United Kingdom of Great Britain and Northern I...
Energy Supply in Gigajoules                                               7920.0
Energy Supply per Capita                                                   124.0
% Renewable                                                             10.60047
Name: 214, dtype: object

In [25]:
pd.set_option("max_colwidth",None)

In [26]:
Energy.replace('United Kingdom of Great Britain and Northern Ireland19','United Kingdom of Great Britain and Northern Ireland19',inplace=True)

In [27]:
pd.set_option('display.max_rows',10)

In [28]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
...,...,...,...,...
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [29]:
Energy.describe().T

,count,mean,std,min,25%,50%,75%,max
Energy Supply in Gigajoules,222.0,2457.981982,11039.145412,0.0,33.000000,189.50000,996.25000,127191.0
Energy Supply per Capita,222.0,90.666667,116.234887,2.0,21.250000,51.00000,117.75000,957.0
% Renewable,227.0,28.086077,31.903505,0.0,0.022893,14.81481,50.16862,100.0

In [30]:
Energy.isnull()

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,True,True,False
4,False,False,False,False
...,...,...,...,...
222,False,False,False,False
223,False,False,False,False
224,False,False,False,False
225,False,False,False,False
226,False,False,False,False

In [32]:
Energy['Energy Supply in Gigajoules'] = Energy['Energy Supply in Gigajoules']*1000000

In [33]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
...,...,...,...,...
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120

In [34]:
pd.set_option('display.max_columns',None)

In [35]:
Energy

,Country,Energy Supply in Gigajoules,Energy Supply per Capita,% Renewable
0,Afghanistan,3.210000e+08,10.0,78.669280
1,Albania,1.020000e+08,35.0,100.000000
2,Algeria,1.959000e+09,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.000000e+06,121.0,88.695650
...,...,...,...,...
222,Viet Nam,2.554000e+09,28.0,45.321520
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.000000
224,Yemen,3.440000e+08,13.0,0.000000
225,Zambia,4.000000e+08,26.0,99.714670
226,Zimbabwe,4.800000e+08,32.0,52.536120